# Generated by Django 4.2.4 on 2023-08-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
