# Generated by Django 4.2.4 on 2023-08-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_views_count_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='ip адрес'),
        ),
    ]
