# Generated by Django 4.2.4 on 2023-08-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_viewcount_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcount',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='viewcount',
            name='articles_vi_viewed__5cd344_idx',
        ),
        migrations.RemoveField(
            model_name='viewcount',
            name='viewed_on',
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='articles.article'),
        ),
    ]
